### ISSUE TITLE
Score IDs and endpoint has been changed

### ISSUE THREAD

**Issue by KaiWhen** [tybug/ossapi#76]
There seems to be new score IDs for all scores which makes retrieving a score using the older endpoint not work with the new score IDs. The endpoint has changed from 'scores/{mode}/{score_id}' to 'scores/{score_id}' although the older endpoint still works with the older score IDs.

**Comment by tybug** [comment]
yeah, I need to figure out a path forward for the new ids here. I will probably add a new method to `Ossapi` for the new ids.

**Comment by tybug** [comment]
I've added endpoints for new score ids in v4.0.0beta1, if you want to try it out: https://github.com/tybug/ossapi/releases/tag/v4.0.0beta1

**Comment by tybug** [comment]
This is available in v4.0.0 proper, which I've just released.
