### ISSUE TITLE
help | Getting a user's recent score

### ISSUE THREAD

**Issue by br0k3V** [tybug/ossapi#81]
So I'm continuing from that other issue, How do I get a user's recent score?
![image](https://github.com/tybug/ossapi/assets/167619285/e4bc8515-b495-4dd0-b336-252a8c6a441b)
Something like this, I can't seem to find anything on the documentation.

**Comment by Stedoss** [comment]
You can get a user's recent scores by using this endpoint function with the "recent" `ScoreType`: https://tybug.github.io/ossapi/users.html#ossapi.ossapiv2.Ossapi.user_scores

```py
from ossapi import Ossapi, ScoreType

api = Ossapi(client_id, client_secret)
api.user_scores(7562902, ScoreType.RECENT)
# api.user_scores(7562902, "recent") also works
```

The latest score should be in the first element of the returned list:
```py
api.user_scores(7562902, "recent")[0]
```

**Comment by br0k3V** [comment]
> You can get a user's recent scores by using this endpoint function with the "recent" `ScoreType`: https://tybug.github.io/ossapi/users.html#ossapi.ossapiv2.Ossapi.user_scores
> 
> ```python
> from ossapi import Ossapi, ScoreType
> 
> api = Ossapi(client_id, client_secret)
> api.user_scores(7562902, ScoreType.RECENT)
> # api.user_scores(7562902, "recent") also works
> ```
> 
> The latest score should be in the first element of the returned list:
> 
> ```python
> api.user_scores(7562902, "recent")[0]
> ```

Thanks, I'll try this.

**Comment by br0k3V** [comment]
Thanks for your help
