### ISSUE TITLE
Python 3.12+ raises SyntaxWarnings for invalid escape sequences in docstrings

### ISSUE THREAD

**Issue by Syriiin** [tybug/ossapi#84]
More just annoying and noisy than anything but, in python 3.12+ the following warning is raised due to the `\s` escapes in various `ModCombination` docstrings like ```:class:`~.ModCombination`\s```.

```
/opt/appdeps/.venv/lib/python3.12/site-packages/ossapi/mod.py:102: SyntaxWarning: invalid escape sequence '\s'
  """
/opt/appdeps/.venv/lib/python3.12/site-packages/ossapi/mod.py:136: SyntaxWarning: invalid escape sequence '\s'
  """
/opt/appdeps/.venv/lib/python3.12/site-packages/ossapi/mod.py:193: SyntaxWarning: invalid escape sequence '\s'
  """
```

I assume the `\s` are there for a reason? Something to do with sphinx syntax?

**Comment by tybug** [comment]
ah, that's annoying. Yeah, it's intentional for sphinx. I forget what happens if you don't have the backslash; I think it probably just fails to compile the docs. I want it pluralized but without a link on the s itself.

I've made the strings raw which should fix this. Thanks for letting me know!
