### ISSUE TITLE
legacy_only seems to have no effect

### ISSUE THREAD

**Issue by reinum** [tybug/ossapi#85]
as the title says

in lazer scoring, a score im requesting is a B rank. ossapi returns a B rank even if legacy_only is True / 1.
in classic scoring - its a C. what a shame.

`last_score = api.user_scores(uid, "best", mode="osu", limit=20, legacy_only=1)[8]`

uid in this case is 14590071
scoreid 3577491652

ossapi updated to the latest version

would love some help with this

**Comment by tybug** [comment]
`legacy_only` is only for excluding lazer scores. It won't change anything about the attributes in the scores which are returned.

For that, set `[api_version](https://github.com/tybug/ossapi/releases/tag/v5.0.0)` to something low like `20200101 ` when instantiating `Ossapi`
